import request from "./request";

export const api = {
  login(data) { return request.post("/user/login", data); },
  register(data) { return request.post("/user/register", data); },
  forgotPassword(data) { return request.post("/user/forgot-password", data); },
  resetPassword(data) { return request.post("/user/reset-password", data); },
  me() { return request.get("/user/me"); },
  logout() { return request.post("/user/logout"); },
  cancelAccount() { return request.post("/user/cancel"); },
  updateMe(data) { return request.put("/user/me", data); },
  changePassword(data) { return request.post("/user/change-password", data); },
  recharge(data) { return request.post("/user/recharge", data); },
  exchangePoints(data) { return request.post("/user/points/exchange", data); },
  addressList() { return request.get("/address/list"); },
  defaultAddress() { return request.get("/address/default"); },
  addAddress(data) { return request.post("/address/add", data); },
  updateAddress(id, data) { return request.put(`/address/${id}`, data); },
  deleteAddress(id) { return request.delete(`/address/${id}`); },
  setDefaultAddress(id) { return request.put(`/address/${id}/default`); },
  productList(params) { return request.get("/product/list", { params }); },
  productDetail(id) { return request.get(`/product/detail/${id}`); },
  categories() { return request.get("/category/list"); },
  reviewList(productId) { return request.get(`/review/product/${productId}`); },
  addReview(data) { return request.post("/review/add", data); },
  favoriteList() { return request.get("/favorite/list"); },
  addFavorite(productId) { return request.post(`/favorite/${productId}`); },
  removeFavorite(productId) { return request.delete(`/favorite/${productId}`); },
  cartList() { return request.get("/cart/list"); },
  cartAdd(data) { return request.post("/cart/add", data); },
  cartDelete(id) { return request.post("/cart/delete", { id }); },
  cartUpdate(id, data) { return request.post("/cart/update", { id, ...data }); },
  createOrder(data) { return request.post("/order/create", data); },
  createDirectOrder(data) { return request.post("/order/create", data); },
  orderPay(id, data) { return request.post(`/order/${id}/pay`, data); },
  orderList(params) { return request.get("/order/list", { params }); },
  orderDetail(id) { return request.get(`/order/${id}`); },
  orderCancel(id) { return request.post(`/order/${id}/cancel`); },
  orderReceive(id) { return request.post(`/order/${id}/receive`); },
  orderRefund(id) { return request.post(`/order/${id}/refund`); },
  applyAfterSale(orderId, data) { return request.post(`/order/${orderId}/after-sale`, data); },
  myAfterSales() { return request.get("/order/after-sale/my"); },
  adminProducts(params) { return request.get("/admin/products", { params }); },
  adminProductDetail(id) { return request.get(`/admin/products/${id}`); },
  adminProductAdd(data) { return request.post("/admin/product/add", data); },
  adminProductUpdate(id, data) { return request.put(`/admin/products/${id}`, data); },
  adminProductDelete(id) { return request.delete(`/admin/products/${id}`); },
  adminProductStatus(id, status) { return request.put(`/admin/product/${id}/status`, null, { params: { status } }); },
  adminCategories() { return request.get("/admin/categories"); },
  adminCategoryAdd(data) { return request.post("/admin/categories", data); },
  adminCategoryUpdate(id, data) { return request.put(`/admin/categories/${id}`, data); },
  adminCategoryDelete(id) { return request.delete(`/admin/categories/${id}`); },
  adminOrders(params) { return request.get("/admin/orders", { params }); },
  adminOrderDetail(id) { return request.get(`/admin/orders/${id}`); },
  adminOrderShip(id) { return request.post(`/admin/orders/${id}/ship`); },
  adminOrderCancel(id) { return request.post(`/admin/orders/${id}/cancel`); },
  adminOrderRefund(id) { return request.post(`/admin/orders/${id}/refund`); },
  adminAfterSales(params) { return request.get("/admin/after-sale", { params }); },
  adminBrands() { return request.get("/admin/brands"); },
  brands(params) { return request.get("/home/brands", { params }); },
  brandDetail(id) { return request.get(`/home/brand/${id}`); },
  adminBrandDetail(id) { return request.get(`/admin/brands/${id}`); },
  adminBrandAdd(data) { return request.post("/admin/brands", data); },
  adminBrandUpdate(id, data) { return request.put(`/admin/brands/${id}`, data); },
  adminBrandDelete(id) { return request.delete(`/admin/brands/${id}`); },
  adminBrandProducts(params) { return request.get("/admin/brands/products", { params }); },
  adminApproveAfterSale(id) { return request.post(`/admin/after-sale/${id}/approve`); },
  adminRejectAfterSale(id, reply) { return request.post(`/admin/after-sale/${id}/reject`, null, { params: { reply } }); },
  adminUsers(params) { return request.get("/admin/users", { params }); },
  adminUserDetail(id) { return request.get(`/admin/users/${id}`); },
  adminUserMeta(id) { return request.get(`/admin/users/${id}/meta`); },
  adminUserDetailWithMeta(id) { return request.get(`/admin/users/${id}/detail`); },
  adminUserLoginRecords(id) { return request.get(`/admin/users/${id}/login-records`); },
  adminUserRecentOrders(id, params) { return request.get(`/admin/users/${id}/recent-orders`, { params }); },
  adminUserAddresses(id) { return request.get(`/admin/users/${id}/addresses`); },
  adminUserStatus(id, status) { return request.put(`/admin/users/${id}/status`, null, { params: { status } }); },
  adminUserRole(id, role) { return request.put(`/admin/users/${id}/role`, null, { params: { role } }); },
  adminReviews(params) { return request.get("/admin/reviews", { params }); },
  adminReviewStatus(id, status) { return request.put(`/admin/reviews/${id}/status`, null, { params: { status } }); },
  adminStatsOverview() { return request.get("/admin/stats/overview"); },
  adminStatsTrend() { return request.get("/admin/stats/trend7d"); },
  homeConfig() { return request.get("/home/config"); },
  adminHomeOperationConfigs() { return request.get("/admin/home-config"); },
  adminHomeOperationConfigCreate(data) { return request.post("/admin/home-config", data); },
  adminHomeOperationConfigUpdate(id, data) { return request.put(`/admin/home-config/${id}`, data); },
  adminHomeOperationConfigDelete(id) { return request.delete(`/admin/home-config/${id}`); },
  adminOperationLogs(params) { return request.get("/admin/logs", { params }); },
  uploadFile(file) {
    const formData = new FormData();
    formData.append("file", file);
    return request.post("/common/upload", formData, {
      headers: { "Content-Type": "multipart/form-data" },
      timeout: 60000
    });
  }
};
